"""
05_generate_final_report.py
----------------------------
Layer 5 — Final output.

Connects to the local isomo_db PostgreSQL database, runs every query in
queries/, and uses the results to produce:

  1. analysis/final_report.md
        A program-lead-readable markdown report answering the core
        question: are the learners who engage the most on Typing and
        Quill the same learners who appear in EFSet, DET, and Northstar
        assessment records, or are there gaps?

  2. analysis/engagement_assessment_summary.csv
        A flat, school-level summary table (built from query 6) that a
        non-technical reader can open directly in Excel/Sheets without
        touching the database.

Run this after 04_load_to_postgres.py has loaded the cleaned data.

Usage:
    python analysis/05_generate_final_report.py
"""

import os
import pandas as pd
from sqlalchemy import create_engine, text

# ── Paths ────────────────────────────────────────────────────────────────────
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
QUERIES_DIR = os.path.join(BASE_DIR, "queries")
ANALYSIS_DIR = os.path.join(BASE_DIR, "analysis")

ENGINE_URL = "postgresql://postgres:postgres123@localhost:5432/isomo_db"

QUERY_FILES = {
    "counts_per_source": "01_learner_counts_per_source.sql",
    "active_schools_typing": "02_most_active_schools_typing.sql",
    "quill_high_low": "03_quill_high_sessions_low_scores.sql",
    "platform_only_no_assessment": "04_platform_only_no_assessment.sql",
    "assessment_coverage": "05_assessment_coverage.sql",
    "school_summary": "06_school_level_summary.sql",
    "engagement_vs_assessment_gap": "07_engagement_vs_assessment_gap.sql",
}


def load_query(filename):
    path = os.path.join(QUERIES_DIR, filename)
    with open(path, "r") as f:
        return f.read()


def run_all_queries(engine):
    """Run every query file and return a dict of {name: DataFrame}."""
    results = {}
    with engine.connect() as conn:
        for name, filename in QUERY_FILES.items():
            sql = load_query(filename)
            print(f"Running {filename} ...")
            try:
                df = pd.read_sql(text(sql), conn)
                results[name] = df
                print(f"  -> {len(df)} rows")
            except Exception as e:
                print(f"  !! Failed: {e}")
                results[name] = pd.DataFrame()
    return results


def build_markdown_report(results):
    counts = results["counts_per_source"]
    no_assessment = results["platform_only_no_assessment"]
    school_summary = results["school_summary"]
    gap = results["engagement_vs_assessment_gap"]

    never_assessed_count = len(no_assessment)
    top_engaged_never_assessed = (
        gap[gap["assessment_status"] == "Never Assessed"]
        if "assessment_status" in gap.columns
        else pd.DataFrame()
    )

    lines = []
    lines.append("# Isomo Data Fellowship — Final Report")
    lines.append("## Learner Engagement & Assessment Gap Analysis\n")
    lines.append("**Fellow:** Nusraty Uwase")
    lines.append("**Generated by:** analysis/05_generate_final_report.py\n")
    lines.append("---\n")

    lines.append("## Data Overview\n")
    lines.append("| Source | Unique Learners |")
    lines.append("|--------|-----------------|")
    for _, row in counts.iterrows():
        first_col = counts.columns[0]
        count_col = counts.columns[-1]
        lines.append(f"| {row[first_col]} | {row[count_col]} |")
    lines.append("")

    lines.append("---\n")
    lines.append("## Key Findings\n")

    lines.append("### 1. Learners active on platforms but never formally assessed")
    lines.append(
        f"Query 4 found **{never_assessed_count} learners** who appear in "
        "Typing or Quill activity logs but have no record in EFSet, DET, "
        "or Northstar. These learners are engaging with the learning tools "
        "but are invisible to the formal assessment system.\n"
    )

    lines.append("### 2. School-level assessment coverage varies sharply")
    lines.append(
        "Query 6 builds a school-level summary of platform activity vs. "
        "assessment coverage. The full table is in "
        "`analysis/engagement_assessment_summary.csv`. Schools with high "
        "platform activity but low assessment counts are the clearest "
        "candidates for assessment-outreach follow-up.\n"
    )

    lines.append("### 3. Top-engagement learners who have never been assessed")
    lines.append(
        f"Query 7 isolated learners in the top 25% of platform engagement. "
        f"**{len(top_engaged_never_assessed)} of them** have never appeared "
        "in any assessment record. This is the sharpest, most actionable "
        "gap identified in this analysis — these learners are clearly "
        "investing time in the platforms but are not being measured.\n"
    )

    lines.append("---\n")
    lines.append("## Recommendations for Programme Leads\n")
    lines.append(
        "1. **Prioritise assessment outreach** for the top-engagement, "
        "never-assessed learners listed in `queries/07_engagement_vs_assessment_gap.sql` "
        "output — they are the easiest wins for closing the gap.\n"
        "2. **Investigate schools** flagged in `engagement_assessment_summary.csv` "
        "with high platform activity but low assessment counts — this may "
        "point to logistical, not motivational, barriers.\n"
        "3. **Standardise on the learner/school ID system** introduced in "
        "this project for all future cohorts, so this matching does not "
        "have to be rebuilt from scratch each time.\n"
    )

    lines.append("---\n")
    lines.append("## How This Report Was Produced\n")
    lines.append(
        "This report was generated programmatically by "
        "`analysis/05_generate_final_report.py`, which connects to the "
        "local `isomo_db` PostgreSQL database, executes every query in "
        "`queries/`, and compiles the results above. Cleaning decisions "
        "are documented in `docs/cleaning_log.md`; ID design decisions are "
        "in `docs/learner_id_design.md` and `docs/school_id_design.md`.\n"
    )

    return "\n".join(lines)


def build_summary_csv(results):
    school_summary = results["school_summary"]
    out_path = os.path.join(ANALYSIS_DIR, "engagement_assessment_summary.csv")
    school_summary.to_csv(out_path, index=False)
    print(f"Wrote {out_path}")


def main():
    engine = create_engine(ENGINE_URL)
    results = run_all_queries(engine)

    report_text = build_markdown_report(results)
    report_path = os.path.join(ANALYSIS_DIR, "final_report.md")
    with open(report_path, "w") as f:
        f.write(report_text)
    print(f"Wrote {report_path}")

    build_summary_csv(results)
    print("\nDone. Final output is in analysis/final_report.md and "
          "analysis/engagement_assessment_summary.csv")


if __name__ == "__main__":
    main()
